english_names = {
    "and": "The Chained Maiden",
    "ant": "The Air Pump",
    "aps": "The Bird of Paradise",
    "aqr": "The Water Bearer",
    "aql": "The Eagle",
    "ara": "The Altar",
    "ari": "The Ram",
    "aur": "The Charioteer",
    "boo": "The Herdsman",
    "cae": "The Chisel",
    "cam": "The Giraffe",
    "cnc": "The Crab",
    "cvn": "The Hunting Dogs",
    "cma": "The Greater Dog",
    "cmi": "The Lesser Dog",
    "cap": "The Sea Goat",
    "car": "The Keel",
    "cas": "The Queen",
    "cen": "The Centaur",
    "cep": "The King",
    "cet": "The Whale (Sea Monster)",
    "cha": "The Chameleon",
    "cir": "The Compasses",
    "col": "The Dove",
    "com": "Berenice's Hair",
    "cra": "The Southern Crown",
    "crb": "The Northern Crown",
    "crv": "The Crow",
    "crt": "The Cup",
    "cru": "The Southern Cross",
    "cyg": "The Swan",
    "del": "The Dolphin",
    "dor": "The Dolphinfish",
    "dra": "The Dragon",
    "equ": "The Little Horse",
    "eri": "The River Eridanus",
    "for": "The Furnace",
    "gem": "The Twins",
    "gru": "The Crane",
    "her": "Hercules",
    "hor": "The Pendulum Clock",
    "hya": "The Water Snake",
    "hyi": "The Lesser Water Snake",
    "ind": "The Indian",
    "lac": "The Lizard",
    "leo": "The Lion",
    "lmi": "The Lesser Lion",
    "lep": "The Hare",
    "lib": "The Scales",
    "lup": "The Wolf",
    "lyn": "The Lynx",
    "lyr": "The Lyre (Harp)",
    "men": "Table Mountain",
    "mic": "The Microscope",
    "mon": "The Unicorn",
    "mus": "The Fly",
    "nor": "The Level",
    "oct": "The Octant",
    "oph": "The Serpent Bearer",
    "ori": "The Hunter",
    "pav": "The Peacock",
    "peg": "The Winged Horse",
    "per": "Perseus",
    "phe": "The Phoenix",
    "pic": "The Painter's Easel",
    "psc": "The Fishes",
    "psa": "The Southern Fish",
    "pup": "The Stern",
    "pyx": "The Compass",
    "ret": "The Reticle",
    "sge": "The Arrow",
    "sgr": "The Archer",
    "sco": "The Scorpion",
    "scl": "The Sculptor",
    "sct": "The Shield",
    "ser": "The Serpent",
    "sex": "The Sextant",
    "tau": "The Bull",
    "tel": "The Telescope",
    "tri": "The Triangle",
    "tra": "The Southern Triangle",
    "tuc": "The Toucan",
    "uma": "The Great Bear",
    "umi": "The Small Bear",
    "vel": "The Sails",
    "vir": "The Virgin",
    "vol": "The Flying Fish",
    "vul": "The Fox",
}